apiVersion: v1
kind: Namespace
metadata:
  name: servicenow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mid-server-deploy
  name: mid-server-deploy
  namespace: servicenow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mid-server-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: mid-server-deploy
      labels:
        app: mid-server-deploy
    spec:
      containers:
        - image: gmmeng/mid-server:latest
          imagePullPolicy: Always
          env:
            - name: MID_INSTANCE_URL
              value: 'https://dev185921.service-now.com'
            - name: MID_INSTANCE_USERNAME
              value: 'mid.user.service'
            - name: MID_INSTANCE_PASSWORD
              value: 'M!d.us3r.'
            - name: MID_SECRETS_FILE
              value: './mid-secrets.properties'
            - name: MID_SERVER_NAME
              value: 'docker-host-$(POD_NAME_SUFFIX)'
            - name: MID_PROXY_HOST
              value: ''
            - name: MID_PROXY_PORT
              value: ''
            - name: MID_PROXY_USERNAME
              value: ''
            - name: MID_PROXY_PASSWORD
              value: ''
            - name: MID_MUTUAL_AUTH_PEM_FILE
              value: ''
            - name: MID_SSL_BOOTSTRAP_CERT_REVOCATION_CHECK
              value: ''
            - name: MID_SSL_USE_INSTANCE_SECURITY_POLICY
              value: ''
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
