apiVersion: v1
kind: Namespace
metadata:
  name: servicenow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mid-server-deploy
  name: mid-server-deploy
  namespace: servicenow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mid-server-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: mid-server-deploy
      labels:
        app: mid-server-deploy
    spec:
      initContainers:
        - name: trivy-installer
          image: ubuntu:latest
          command: ["sh", "-c"]
          args:
            - |
              apt-get update -y
              apt-get install -y wget apt-transport-https gnupg lsb-release
              wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
              dpkg -i trivy_0.18.3_Linux-64bit.deb
              cp $(which trivy) /shared-volume/trivy
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-volume
      containers:
        - name: mid-server
          image: gmmeng/mid-server:latest
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              mkdir /opt/snc_mid_server/agent/work/uploaded_files
              cp /shared-volume/trivy /opt/snc_mid_server/agent/work/uploaded_files/trivy
              /opt/snc_mid_server/init start
              crontab -l > mycron
              echo "* * * * * cp /shared-volume/trivy /opt/snc_mid_server/agent/work/uploaded_files/trivy" >> mycron
              crontab mycron
              rm mycron
              
          env:
            - name: MID_INSTANCE_URL
              value: 'https://dev185921.service-now.com'
            - name: MID_INSTANCE_USERNAME
              value: 'mid.user.service'
            - name: MID_INSTANCE_PASSWORD
              value: 'M!d.us3r.'
            - name: MID_SECRETS_FILE
              value: './mid-secrets.properties'
            - name: MID_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MID_PROXY_HOST
              value: ''
            - name: MID_PROXY_PORT
              value: ''
            - name: MID_PROXY_USERNAME
              value: ''
            - name: MID_PROXY_PASSWORD
              value: ''
            - name: MID_MUTUAL_AUTH_PEM_FILE
              value: ''
            - name: MID_SSL_BOOTSTRAP_CERT_REVOCATION_CHECK
              value: ''
            - name: MID_SSL_USE_INSTANCE_SECURITY_POLICY
              value: ''
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: shared-volume
          emptyDir: {}