# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-02-11T06:22:36Z"
  generation: 1
  labels:
    app: mid-server-deploy
  name: mid-server-deploy
  namespace: servicenow
  resourceVersion: "8493"
  uid: ad2eb479-ba76-4c85-96d7-fd1372495f5d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mid-server-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
template:
  metadata:
    creationTimestamp: null
    labels:
      app: mid-server-deploy
  spec:
    containers:
      - image: gmmeng/mid-server:latest
        imagePullPolicy: Always
        name: mid-server
        env:
          - name: MID_INSTANCE_URL
            value: dev185921.service-now.com
          - name: MID_INSTANCE_USERNAME
            value: mid.user.service
          - name: MID_INSTANCE_PASSWORD
            value: M!d.us3r.
          - name: MID_SECRETS_FILE
            value: ./mid-secrets.properties
          - name: MID_SERVER_NAME
            value: docker-host
          - name: MID_PROXY_HOST
            value: ""
          - name: MID_PROXY_PORT
            value: ""
          - name: MID_PROXY_USERNAME
            value: ""
          - name: MID_PROXY_PASSWORD
            value: ""
          - name: MID_MUTUAL_AUTH_PEM_FILE
            value: ""
          - name: MID_SSL_BOOTSTRAP_CERT_REVOCATION_CHECK
            value: ""
          - name: MID_SSL_USE_INSTANCE_SECURITY_POLICY
            value: ""
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    terminationGracePeriodSeconds: 30